config/routes.rb
Rails.application.routes.draw do
  get "sitemap.xml.gz" => "sitemaps#sitemap", format: :xml, as: :sitemap
  get "/.well-known/acme-challenge/:id" => "homepage#letsencrypt"
  localized do
    devise_for :users
    get 'bot/:permalink' => 'directory#show', as: 'bot_page'
    resources :photos, only: [:index, :create, :destroy]
    resources :selected_bots
    get 'directory/:platform/:category/:language/(:keywords)' => 'directory#index', as: 'directory'
    resources :providers, :bots, :posts
    resources :contacts do
      member do
        put 'completed'
      end
    end
    get 'logos' => 'bots#logos'
    post 'posts/preview' => 'posts#preview', as: 'post_preview'
    get 'admin' => "admin#index", as: 'admin'
    get 'admin/update_bots' => "admin#update_bots"
    post 'admin/manage_bots' => "admin#manage_bots"
    get 'blog/:permalink' => 'blog#show', as: 'blog_article'
    get 'blog' => 'blog#index', as: 'blog'
    root to: 'homepage#index'
  end
end

app/models/bot.rb
  # == Schema Information
#
# Table name: bots
#
#  id                :integer          not null, primary key
#  name              :string
#  description_fr    :text
#  website           :string
#  twitter           :string
#  facebook          :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  categories        :string           is an Array
#  permalink         :string
#  logo_file_name    :string
#  logo_content_type :string
#  logo_file_size    :integer
#  logo_updated_at   :datetime
#  tagline_fr        :string
#  product_hunt_url  :string
#  venture_beat_url  :string
#  languages         :string           is an Array
#  tagline_en        :string
#  description_en    :text
#  tested_on         :date
#  test_en           :text
#  test_fr           :text
#  status            :string           default("pending")
#

class Bot < ApplicationRecord
  has_many :platforms
  accepts_nested_attributes_for :platforms , allow_destroy: true, reject_if: proc { |attributes| attributes['url'].blank? || attributes['provider_id'].nil?}
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :permalink, presence: true, uniqueness: true
  before_validation :create_permalink
  before_save :check_status_change

  has_attached_file :logo,
    styles: { medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/botenstock.png"

  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

  include PgSearch
  pg_search_scope :search_for, against: %i(name description_en tagline_en description_fr tagline_fr)
  scope :ok, -> { where(status: 'ok')}



  STATUSES = ['ok', 'pending', 'discarded', 'incomplete']

  CATEGORIES = [
    'Actualités',
    'Business',
    'Cinéma',
    'Communication',
    'Cuisine/Gastronomie',
    'Dev',
    'Divertissement',
    'Don/Caritatif',
    'Education',
    'Femme',
    'Finance',
    'Fun',
    'Jeux',
    "Marketing",
    'Marque',
    'Paiements',
    'Personnel',
    'Productivité',
    'Réseaux sociaux',
    'Ressources Humaines',
    'Santé',
    'Shopping',
    'Sport',
    'Sécurité',
    'Utilitaires',
    'Voyage'
  ]

  LANGUAGES = ['en', 'fr']

  def platform_url(platform)
    id = Provider.where(code: platform).first
    self.platforms.select{|p| p.provider_id == id}.first.url
  end
  def visible_platforms
    platforms.visible
  end

  def tagline
    send("tagline_#{I18n.locale}")
  end

  def related_bots
    bots = Bot.ok
    categories.each do |cat|
      bots = bots.where(" ? = ANY(categories)", cat)
    end
    bots = bots.where("id != ?", id)
    bots.limit(5)
  end

  def description
    content = send("description_#{I18n.locale}")
    return '' if content.blank?
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    markdown.render(content).html_safe
  end

  def self.migrate_languages
    Bot.all.each do |bot|
      if bot.languages && bot.languages.any?
        languages = bot.languages
        new_languages = []
        new_languages << 'fr' if languages.include?('Français')
        new_languages << 'en' if languages.include?('Anglais')
        bot.languages = new_languages
        bot.save
      end
    end
  end

  private

  def create_permalink
    self.name = name.strip
    self.permalink = name.parameterize.to_s.gsub("_", "-")
    # self.platforms= []
    # PLATFORMS.each do |platform|
    #    self.platforms << platform unless platform_url(platform).blank?
    # end
    self.languages = self.languages.delete_if{|l| l.blank?} if self.languages
    self.categories = self.categories.delete_if{|l| l.blank?} if self.categories
  end

  def check_status_change
    status_changed = self.changes.fetch("status"){nil}
    if status_changed && status_changed[1] == 'ok'
      self.created_at = Time.now
    end
  end

end

app/controllers/bots_controller.rb
require 'bootstrap_table.rb'

class BotsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_admin, only: [:index, :destroy]
  before_action :set_bot, only: [:show, :edit, :update, :destroy]
  layout "admin"

  def logos
    @bots = Bot.all.order('created_at desc')
  end

  # GET /bots
  # GET /bots.json
  def index
    respond_to do |format|
      format.html
      format.json {
        bots = Bot.all
        bots = bots.where(status: params[:status]) unless params[:status].blank?
        bots = bots.where(" ? = ANY(categories)", params[:category]) unless params[:category].blank?
        bots = bots.joins(:platforms).where("platforms.provider_id = ?", params[:platform].to_i) unless params[:platform].blank?
        bots = bots.where(" ? = ANY(languages)", params[:language]) unless params[:language].blank?
        bots = bots.search_for(params[:search]) unless params[:search].blank?
        bots = bots.includes(platforms: :provider)
        if params[:sort] && params[:order]
          bots = bots.order("#{params[:sort]} #{params[:order]}")
        else
          bots = bots.order('name asc')
        end
        render json: BootstrapTable.
                      new(bots.to_sql).
                      json( start: params[:offset].to_i,
                            per_page: params[:limit].to_i
                      )
      }
    end
  end

  # GET /bots/1
  # GET /bots/1.json
  def show
    redirect_to bot_page_path(permalink: @bot.permalink)
  end

  # GET /bots/new
  def new
    @bot = Bot.new
    @bot.status = current_user.has_role?('admin') ? 'ok' : 'pending'
    add_platforms
    @translated_links = {}
    @translated_links[:en] = new_bot_en_path if I18n.locale != :en
    @translated_links[:fr] = new_bot_fr_path if I18n.locale != :fr

  end

  # GET /bots/1/edit
  def edit
    add_platforms
  end

  # POST /bots
  # POST /bots.json
  def create
    @bot = Bot.new(bot_params)

    respond_to do |format|
      if @bot.save
        format.html { redirect_to @bot, notice: 'Le bot a été créé.' }
        format.json { render :show, status: :created, location: @bot }
      else
        format.html { render :new }
        format.json { render json: @bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bots/1
  # PATCH/PUT /bots/1.json
  def update
    respond_to do |format|
      if @bot.update(bot_params)
        format.html { redirect_to @bot, notice: 'Le bot a été mis à jour.' }
        format.json { render :show, status: :ok, location: @bot }
      else
        format.html { render :edit }
        format.json { render json: @bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bots/1
  # DELETE /bots/1.json
  def destroy
    @bot.destroy
    respond_to do |format|
      format.html { redirect_to bots_url, notice: 'Le bot a été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bot
      @bot = Bot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bot_params
      params.require(:bot).permit(
        :name,
        :status,
        :description_fr,
        :description_en,
        :tested_on,
        :test_fr,
        :test_en,
        :logo,
        :website,
        :twitter,
        :facebook,
        :tagline_en,
        :tagline_fr,
        :comments,
        :product_hunt_url,
        :venture_beat_url,
        categories: [],
        languages: [],
        platforms_attributes: [:url, :provider_id, :id]
      )
    end

    def add_platforms
      Provider.all.each do |provider|
        unless @bot.platforms.map(&:provider_id).include? provider.id
          @bot.platforms << Platform.new(provider_id: provider.id)
        end
      end
    end
end

app/helpers/bots_helper.rb
module BotsHelper
end

app/views/bots/_bot.html.erb
<a href="<%= bot_path(bot.permalink)%>">
  <div class='card col-md-12'>
    <div class='pull-left'>
      <%= image_tag bot.logo.url(:thumb) , class:'img-rounded', alt: bot.name%>
    </div>
    <div>
      <h4 class="media-heading"><%= bot.name%></h4>
      <div class='tagline'><%=bot.tagline%></div>
      <% unless bot.categories.nil?%>
        <%= bot.categories.map{|c| "<span class='label label-default'>#{I18n.t("category.list.#{c}")}</span>"}.join(' ').html_safe %><br>
      <%end%>
      <% unless bot.platforms.empty?%>
        <%= bot.platforms.visible.map{|p| "<span class='label label-default'>#{p.provider.name}</span>"}.join(' ').html_safe %><br>
      <%end%>
      </div>
  </div>
</a>

app/views/bots/_button_bar.html.erb
<div class="button-bar">
  <%= f.button :submit , value: I18n.t('save'), class: 'btn-primary'%>
  <%= link_to( I18n.t('show'), bot_page_path(permalink:@bot.permalink), class:'btn btn-default' ) if @bot.persisted?%>
  <%= link_to I18n.t('return'), :back , class:'btn btn-default'%>
  <%= link_to I18n.t('delete') , bot_path(@bot), method: :delete, class: 'btn btn-danger',data: { confirm: I18n.t('sure?') } if @bot.persisted?%>
</div>

app/views/bots/_form.html.erb
<%= simple_form_for(@bot, html: { class: 'form-horizontal ' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  }) do |f| %>

    <%= render 'button_bar', f: f  %>


    <%= f.error_notification %>
    <%= f.input :name %>
    <%if current_user.has_role?(:admin)%>
        <%= f.input :status,
            collection: Bot::STATUSES ,
            input_html: { class: 'col-md-4' }
        %>

    <h3>Taglines</h3>
    <%= f.input :tagline_en %>
    <%= f.input :tagline_fr %>
    <h3>Descriptions</h3>
    <%= f.input :description_en, input_html: {rows: 5 }%>
    <%= f.input :description_fr, input_html: {rows: 5 } %>

        <h3>Test</h3>
            <%= f.input :test_en, input_html: {rows: 5 }%>
            <%= f.input :test_fr, input_html: {rows: 5 } %>
            <%= f.input :tested_on, as: :date, html5: true, wrapper: :horizontal_form%>
    <%end%>
    <%= f.input :website , as: :url, placeholder: 'http://example.com'%>

    <%if current_user.has_role?(:admin)%>
        <%= f.input :product_hunt_url , as: :url, placeholder: 'http://example.com'%>
        <%= f.input :venture_beat_url , as: :url, placeholder: 'http://example.com'%>
    <%end%>
    <%= f.input :categories,
        as: :check_boxes,
        collection: Bot::CATEGORIES.sort{|x,y| t("category.list.#{x}") <=> t("category.list.#{y}")} ,
        label_method: ->(obj){ t("category.list.#{obj}") }
    %>
    <%= f.input :languages,
        as: :check_boxes,
        collection: Bot::LANGUAGES,
        label_method: ->(obj){ t("language.list.#{obj}") }
    %>
    <%= f.input :twitter %>
    <%= f.input :facebook %>
    <%if current_user.has_role?(:admin)%>
    <%= f.input :logo, as: :file %>
    <%end%>
  <h3><%=I18n.t('simple_form.labels.bot.platforms')%></h3>
    <%= f.simple_fields_for :platforms, f.object.platforms.sort_by{|p| p.provider_name} do |p| %>
      <%= p.input :url, as: :url, label: p.object.provider.name,  placeholder: 'http://example.com'%>
      <%= p.hidden_field :provider_id%>
    <% end %>
    <hr>
    <%= f.input :comments, input_html: {rows: 5 } %>
    <%= render 'button_bar', f: f %>
<% end %>

app/views/bots/_search_box.html.erb
<div class="col-sm-12 search-box">
  <div class="container">
    <%= form_tag bots_path , method: :get, class: 'col-md-8 col-md-offset-2' do%>
      <div class='logos'>
        <% Provider.visible.all.each do |provider|%>
          <%=  image_tag provider.icon.url(:thumb)%>
        <%end%>
      </div>
      <div class='input-group'>
        <%= search_field_tag 'keywords', params[:keywords], class:'form-control', placeholder: I18n.t('search_placeholder') %>
        <span class='input-group-btn'>
          <%= button_tag I18n.t('search'), class: "btn btn-secondary"%>
        </span>
      </div>
    <%end%>
  </div>
</div>

app/views/bots/edit.html.erb
<div class='container bg-white'>
  <h1>Editer le Bot</h1>
  <%= render 'form', bot: @bot %>
</div>

app/views/bots/index.html.erb
<h1><span id='bot_number'></span>Bots </h1>

<div class="button-bar">
  <%=link_to I18n.t('add_bot'), new_bot_path, class: 'btn btn-primary'%>
</div>

<div id="toolbar">
<div class='col-sm-4'>
  <%= select_tag :category, options_for_select(Bot::CATEGORIES, params[:category], ),  class: 'form-control input-sm', id:'category',include_blank: I18n.t('category.all')%>
</div>
<div class='col-sm-4'>
  <%= select_tag :platform,
      options_for_select(
        Provider.all.map{|p| [p.name, p.id]},
        params[:platform]
      ),
      class: 'form-control input-sm', id:'platform',include_blank: I18n.t('platform.all')%>
</div>
<div class='col-sm-4'>
  <%= select_tag :status, options_for_select(Bot::STATUSES, params[:status], ),  class: 'form-control input-sm', id:'status',include_blank: I18n.t('status.all')%>
</div>
</div>

<table class='table table-hover table-condensed table-striped' id="bots"
       data-side-pagination="server"
       data-pagination="true"
       data-search="true"
       data-show-refresh="true"
       data-toolbar="#toolbar"
       data-page-size='50'
       data-show-columns="true"
       data-unique-id="id"
>
  <thead>
    <tr>
      <th>Id</th>
      <th><%=I18n.t('simple_form.labels.bot.name')%></th>
      <th><%=I18n.t('simple_form.labels.bot.created_at')%></th>
      <th><%=I18n.t('simple_form.labels.bot.updated_at')%></th>
      <th>Status</th>
      <th><%=I18n.t('simple_form.labels.bot.categories')%></th>

    </tr>
  </thead>
  <tbody style="cursor: pointer">
  </tbody>
</table>

app/views/bots/logos.html.erb
<h1>Logos</h1>
<%@bots.each do |bot|%>
<div style='float: left; width: 105px; height: 105px;'>
  <a href="<%= edit_bot_path(bot)%>">
    <%= image_tag bot.logo.url(:thumb) , class:'img-rounded', alt: bot.name%>
  </a>
</div>
<%end%>

app/views/bots/new.html.erb
<div class='container bg-white'>
  <h1>Soumettre un Nouveau Bot</h1>

  <%= render 'form', bot: @bot %>
</div>