config/routes.rb
Rails.application.routes.draw do
  get "sitemap.xml.gz" => "sitemaps#sitemap", format: :xml, as: :sitemap
  get "/.well-known/acme-challenge/:id" => "homepage#letsencrypt"
  localized do
    devise_for :users
    get 'bot/:permalink' => 'directory#show', as: 'bot_page'
    resources :photos, only: [:index, :create, :destroy]
    resources :selected_bots
    get 'directory/:platform/:category/:language/(:keywords)' => 'directory#index', as: 'directory'
    resources :providers, :bots, :posts
    resources :contacts do
      member do
        put 'completed'
      end
    end
    get 'logos' => 'bots#logos'
    post 'posts/preview' => 'posts#preview', as: 'post_preview'
    get 'admin' => "admin#index", as: 'admin'
    get 'admin/update_bots' => "admin#update_bots"
    post 'admin/manage_bots' => "admin#manage_bots"
    get 'blog/:permalink' => 'blog#show', as: 'blog_article'
    get 'blog' => 'blog#index', as: 'blog'
    root to: 'homepage#index'
  end
end

app/models/selected_bot.rb
class SelectedBot < ApplicationRecord
  belongs_to :bot
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :greater_than_start
  def self.draw(item_numbers = 1)
    SelectedBot.where('now() between start_date and end_date').order('random()').limit(item_numbers).map(&:bot)
  end

  private

  def greater_than_start
    errors.add(:end_date, I18n.t("activerecord.errors.models.selected_bot.attributes.end_date.wrong")) unless self.end_date > self.start_date
  end
end

app/controllers/selected_bots_controller.rb
class SelectedBotsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_admin
  before_action :set_selected_bot, only: [:show, :edit, :update, :destroy]
  layout "admin"
  # GET /selected_bots
  # GET /selected_bots.json
  def index
    @selected_bots = SelectedBot.all
    @selected_bots = @selected_bots.order('end_date desc').paginate(:page => params[:page], :per_page => 20)
  end

  # GET /selected_bots/1
  # GET /selected_bots/1.json
  def show
    redirect_to selected_bots_path
  end

  # GET /selected_bots/new
  def new
    @selected_bot = SelectedBot.new
  end

  # GET /selected_bots/1/edit
  def edit
  end


  # POST /selected_bots
  # POST /selected_bots.json
  def create
    @selected_bot = SelectedBot.new(selected_bot_params)

    respond_to do |format|
      if @selected_bot.save
        format.html { redirect_to @selected_bot, notice: 'La sélection a été créée.' }
        format.json { render :show, status: :created, location: @selected_bot }
      else
        format.html { render :new }
        format.json { render json: @selected_bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selected_bots/1
  # PATCH/PUT /selected_bots/1.json
  def update
    respond_to do |format|
      if @selected_bot.update(selected_bot_params)
        format.html { redirect_to selected_bots_path, notice: 'La sélection a été mise à jour.' }
        format.json { render :show, status: :ok, location: @selected_bot }
      else
        format.html { render :edit }
        format.json { render json: @selected_bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selected_bots/1
  # DELETE /selected_bots/1.json
  def destroy
    @selected_bot.destroy
    respond_to do |format|
      format.html { redirect_to selected_bots_url, notice: 'La sélection a été supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selected_bot
      @selected_bot = SelectedBot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selected_bot_params
      params.require(:selected_bot).permit(:bot_id, :start_date, :end_date)
    end
end

app/views/selected_bots/_form.html.erb
<%= simple_form_for(@selected_bot, html: { class: 'form-horizontal ' },
  wrapper: :horizontal_form,
    wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  }) do |f| %>

    <%= f.error_notification %>
    <div class="button-bar">
      <%= f.button :submit , value: I18n.t('save'), class: 'btn-primary'%>
      <%= link_to I18n.t('return'), selected_bots_path , class:'btn btn-default'%>
      <%= link_to I18n.t('delete') , selected_bot_path(@selected_bot), method: :delete, class: 'btn btn-danger', data: { confirm: I18n.t('sure?') } if @selected_bot.persisted?%>
    </div>

    <%= f.association :bot, collection: Bot.order(:name)%>
    <%= f.input :start_date, as: :date, html5: true %>
    <%= f.input :end_date, as: :date, html5: true %>
<% end %>

app/views/selected_bots/edit.html.erb
<div class='container bg-white'>
  <h1><%=I18n.t('edit')%></h1>

  <%= render 'form', selected_bot: @selected_bot %>
  </div>

app/views/selected_bots/index.html.erb
<h1><%= SelectedBot.count%> Seleted Bots </h1>

<table class='table table-hover table-condensed table-striped'>
  <thead>
    <tr>
      <th><%=I18n.t('simple_form.labels.bot.name')%></th>
      <th colspan=2>Dates</th>

    </tr>
  </thead>
  <tbody>
    <% @selected_bots.each do |selected_bot| %>
      <tr>
        <td><%=link_to selected_bot.bot.name, edit_selected_bot_path(selected_bot) %></td>
        <td><%=selected_bot.start_date%></td>
        <td><%=selected_bot.end_date%></td>
      </tr>
    <%end%>
  </tbody>
</table>
<%= will_paginate @selected_bots, class:'apple_pagination' %>
<div class="button-bar">
  <%=link_to "Add", new_selected_bot_path, class: 'btn btn-primary'%>
</div>

app/views/selected_bots/new.html.erb
<div class='container bg-white'>
  <h1>New Selected Bot</h1>

  <%= render 'form', selected_bot: @selected_bot %>
  </div>