config/routes.rb
Rails.application.routes.draw do
  get "sitemap.xml.gz" => "sitemaps#sitemap", format: :xml, as: :sitemap
  get "/.well-known/acme-challenge/:id" => "homepage#letsencrypt"
  localized do
    devise_for :users
    get 'bot/:permalink' => 'directory#show', as: 'bot_page'
    resources :photos, only: [:index, :create, :destroy]
    resources :selected_bots
    get 'directory/:platform/:category/:language/(:keywords)' => 'directory#index', as: 'directory'
    resources :providers, :bots, :posts
    resources :contacts do
      member do
        put 'completed'
      end
    end
    get 'logos' => 'bots#logos'
    post 'posts/preview' => 'posts#preview', as: 'post_preview'
    get 'admin' => "admin#index", as: 'admin'
    get 'admin/update_bots' => "admin#update_bots"
    post 'admin/manage_bots' => "admin#manage_bots"
    get 'blog/:permalink' => 'blog#show', as: 'blog_article'
    get 'blog' => 'blog#index', as: 'blog'
    root to: 'homepage#index'
  end
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="bg-white">
  <div class="container">
    <div class="col-sm-12 text-center">
      <p>
        <%= link_to 'Contact', new_contact_path%> | <%= link_to 'Blog', blog_path if current_user && current_user.has_role?(:admin)%> | <a href='https://www.facebook.com/botsforchatting'>Facebook</a> | <%=link_to I18n.t('submit_bot'), new_bot_path if current_user%>
      </p>
      <p>Made with <span class="glyphicon glyphicon-heart text-danger" aria-hidden="true"></span> in Paris by Bots for Chatting</p>
    </div>
  </div>
</footer>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env.production? && (current_user.nil? || ! current_user.has_role?(:admin))%>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-91923309-1', 'auto');
    ga('send', 'pageview');
  </script>
<%end%>

app/views/layouts/_icons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo-header.png'), root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li>
  <%= link_to 'Blog', blog_path %>
</li>
<li>
  <%= link_to 'Admin', admin_path if current_user && current_user.has_role?(:admin)%>
</li>
<li>
  <% if I18n.locale == :fr %>
    <%= link_to "English", (@translated_links && @translated_links[:en]) || root_en_path() %>

  <% else %>
    <%= link_to "Français", (@translated_links && @translated_links[:fr]) || root_fr_path() %>

  <%end%>
</li>
<% if user_signed_in?%>
<li><%= link_to t("devise.shared.links.sign_out"), destroy_user_session_path, method: :delete %></li>
<%else%>
<li><%= link_to t("devise.shared.links.sign_up"), new_user_registration_path %></li>
<li><%= link_to t("devise.shared.links.sign_in"), new_user_session_path %></li>
<%end%>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Botenstock" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  </head>
  <body>
    <nav>
      <%= render 'layouts/navigation' %>
    </nav>
    <div class='container-fluid'>
      <div class='admin-container row'>
        <div class='sidebar col-md-2'>
          <a href="<%=admin_path()%>">
            Statistiques
          </a>

          <a href="<%=providers_path()%>">
            <%= I18n.t('provider', count: 2).titlecase %>
            <span class="badge"><%=Provider.count%></span>
          </a>
          <a href="<%=bots_path()%>">
            Bots
            <span class="badge"><%=Bot.count%></span>
          </a>
          <a href="<%=posts_path()%>">
            <%= I18n.t('post', count: Post.count).titlecase %>
            <span class="badge"><%=Post.count%></span>
          </a>
          <a href="<%=photos_path()%>">
            Photos
            <span class="badge"><%=Photo.count%></span>
          </a>
          <a href="<%=contacts_path()%>">
            Contacts
            <span class="badge"><%=Contact.pending.count%></span>
          </a>
          <a href="<%=selected_bots_path()%>">
            Selected bots
            <span class="badge"><%=SelectedBot.count%></span>
          </a>

          <a href="<%=logos_path()%>">
            Logos
          </a>
        </div>
        <div class='col-md-10'>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%=I18n.locale%>">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= render 'layouts/icons' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= display_meta_tags site: 'Bots for Chatting'%>
    <%= render 'layouts/google_analytics' %>  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/old_mailer_1489672120.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/old_mailer_1489672445.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />

    <%= stylesheet_link_tag "foundation_emails" %>
  </head>

  <body>
    <table class="body" data-made-with-foundation>
      <tr>
        <td class="center" align="center" valign="top">
          <center>
            <%= yield %>
          </center>
        </td>
      </tr>
    </table>
  </body>
</html>